tools:
  # we want to use a pinned version of binny to manage the toolchain (so binny manages itself!)
  - name: binny
    version:
#      want: v0.8.0
      want: fix-freebsd
    method: go-install
    with:
      module: github.com/anchore/binny
      entrypoint: cmd/binny

  # used to produce SBOMs during release
  - name: syft
    version:
      want: latest
    method: go-install
    with:
      module: github.com/anchore/syft
      entrypoint: cmd/syft

  # used to sign mac binaries at release
  - name: quill
    version:
      want: v0.4.1
    method: go-install
    with:
      module: github.com/anchore/quill
      entrypoint: cmd/quill

  # used for linting
  - name: golangci-lint
    version:
      want: v1.59.1
    method: github-release
    with:
      repo: golangci/golangci-lint

  # used for showing the changelog at release
  - name: glow
    version:
      want: v1.5.1
    method: github-release
    with:
      repo: charmbracelet/glow

  # used for signing the checksums file at release
  - name: cosign
    version:
      want: v2.2.4
    method: go-install
    with:
      module: github.com/sigstore/cosign/v2
      entrypoint: cmd/cosign

  # used in integration tests to verify JSON schemas
  - name: yajsv
    version:
      want: v1.4.1
    method: go-install
    with:
      module: github.com/neilpa/yajsv
      entrypoint:

  # used to release all artifacts
  - name: goreleaser
    version:
      want: v2.0.1
    method: go-install
    with:
      module: github.com/goreleaser/goreleaser/v2
#      entrypoint: cmd

  # used for organizing imports during static analysis
  - name: gosimports
    version:
      want: v0.3.8
    method: go-install
    with:
      module: github.com/rinchsan/gosimports
      entrypoint: cmd/gosimports

  # used at release to generate the changelog
  - name: chronicle
    version:
      want: v0.8.0
    method: go-install
    with:
      module: github.com/anchore/chronicle
      entrypoint: cmd/chronicle

  # used during static analysis for license compliance
  - name: bouncer
    version:
      want: v0.4.0
    method: go-install
    with:
      module: github.com/wagoodman/go-bouncer
      entrypoint:

  # used for showing benchmark testing
  - name: benchstat
    version:
      want: latest
      method: go-proxy
      with:
        module: golang.org/x/perf
        allow-unresolved-version: true
    method: go-install
    with:
      entrypoint: cmd/benchstat
      module: golang.org/x/perf

  # used for running all local and CI tasks
  - name: task
    version:
      want: v3.37.2
    method: github-release
    with:
      repo: go-task/task

  # used for triggering a release
  - name: gh
    version:
      want: v2.51.0
    method: go-install
    with:
      module: github.com/cli/cli/v2
      entrypoint: cmd/gh
