release:
  prerelease: auto
  draft: false

env:
  # required to support multi architecture docker builds
  - DOCKER_CLI_EXPERIMENTAL=enabled

builds:
  - id: darwin-build
    dir: ./cmd/syft
    binary: syft
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: .tmp/quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log
