project_name: syft

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - LATEST_TAG=,latest

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
- id: linux
  binary: syft-linux-{{ .Arch }}
  no_unique_dist_dir: true
  main: ./cmd/syft
  flags:
    - -trimpath
  mod_timestamp: '{{ .CommitTimestamp }}'
  goos:
    - linux
  goarch:
    - amd64
    - arm64
    - arm
    - s390x
    - ppc64le
  goarm:
    - '7'
  ldflags:
    - "{{ .Env.LDFLAGS }}"

- id: darwin-amd64
  binary: syft-darwin-amd64
  no_unique_dist_dir: true
  main: ./cmd/syft
  flags:
    - -trimpath
  mod_timestamp: '{{ .CommitTimestamp }}'
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - "{{ .Env.LDFLAGS }}"

      # nfpms:
      # archives:
      # checksum:
      # snapshot:
release:
  prerelease: allow
  draft: true
  github:
    owner: anchore
    name: syft
  footer: |
    ### Thank you OSS contributors!
