# fixture is not under test, just used to produde the uv.lock
[project]
name = "testpkg"
version = "0.1.0"

dependencies = [
    "httpx[brotli,http2,socks]>=0.27.0,<0.30.0",
    "pygments==2.15.0",
    "click<8",
    "rich<10"
]
