# Note: changes to this file will result in updating several test values. Consider making a new image fixture instead of editing this one.
FROM scratch

LABEL org.opencontainers.image.ref.name="scratch"
LABEL org.opencontainers.image.version="latest"

ADD file-1.txt /somefile-1.txt
ADD file-2.txt /somefile-2.txt
