# Based on the Yocto Project Quick Build guide: https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html
FROM debian:stable-slim AS build

RUN apt-get update && apt-get install -y \
    build-essential chrpath cpio debianutils diffstat file gawk gcc git \
    iputils-ping libacl1 libcrypt-dev locales python3 python3-git \
    python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo \
    unzip wget xz-utils zstd

ADD https://git.openembedded.org/bitbake.git /opt/bitbake

ENV LANG=en_GB.UTF-8
RUN sed -i -e '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

RUN useradd -m -s /bin/bash user

USER user
WORKDIR /home/user

RUN /opt/bitbake/bin/bitbake-setup init --non-interactive poky-wrynose poky machine/qemux86-64 distro/poky-tiny

# Cofigure to build IPK packages
COPY <<EOF /home/user/bitbake-builds/poky-tiny-wrynose/build/conf/local.conf
PACKAGE_CLASSES ?= "package_ipk"
EOF

# Build the zlib package
RUN . /home/user/bitbake-builds/poky-tiny-wrynose/build/init-build-env && bitbake zlib

USER root
RUN find /home/user/bitbake-builds/poky-tiny-wrynose/build/tmp/deploy/ipk -name 'libz1_*.ipk' -execdir cp -v '{}' / \;

FROM scratch AS final
COPY --from=build /*.ipk /
