# same as --file; write output report to a file (default is to write to stdout)
file: "test-explicit-config"
package:
  cataloger:
    scope: "squashed"

    # same as --scope; limit the scope of the cataloger to only the specified types