FROM alpine:3.6
RUN apk update && apk add python3 wget curl unzip make ca-certificates jq
# verifying sigstore bundles (releases >= v1.53.0) requires cosign v2.5.0 or newer
RUN curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64" && \
    mv cosign-linux-amd64 /usr/local/bin/cosign && \
    chmod +x /usr/local/bin/cosign
