# This file created by conda-build 2.1.4
# meta.yaml template originally from:
# /recipe_root, last modified Fri Feb 24 14:43:51 2017
# ------------------------------------------------

package:
    name: arrow-cpp
    version: 0.2.post
source:
    fn: f6924ad83bc95741f003830892ad4815ca3b70fd.tar.gz
    sha256: d78fcb18284ce043f3375096deaed83ff491c95237e9ba3ec5349a1c760fb14b
    url: https://github.com/apache/arrow/archive/f6924ad83bc95741f003830892ad4815ca3b70fd.tar.gz
build:
    number: '0'
    string: '0'
requirements:
    build: []
    run:
        - jemalloc
test:
    commands:
        - test -f $PREFIX/lib/libarrow.a
        - test -f $PREFIX/lib/libarrow.so
        - test -f $PREFIX/lib/libarrow_io.a
        - test -f $PREFIX/lib/libarrow_io.so
        - test -f $PREFIX/lib/libarrow_ipc.a
        - test -f $PREFIX/lib/libarrow_ipc.so
        - test -f $PREFIX/lib/libarrow_jemalloc.so
about:
    home: http://github.com/apache/arrow
    license: Apache 2.0
    summary: C++ libraries for Apache Arrow
extra:
    recipe-maintainers:
        - wesm
        - xhochy
