jobs:

  call-workflow-1-in-local-repo:
    uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89

  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/workflow-2.yml

  call-workflow-in-another-repo:
    uses: octo-org/another-repo/.github/workflows/workflow.yml@v1


  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap environment
        run: make unit
