# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr  6 22:31:31 2020
# ------------------------------------------------

package:
    name: jupyterlab
    version: 2.1.0
source:
    fn: jupyterlab-2.1.0.tar.gz
    sha256: 8c239aababf5baa0b3d36e375fddeb9fd96f3a9a24a8cda098d6a414f5bbdc81
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-2.1.0.tar.gz
build:
    entry_points:
        - jlpm = jupyterlab.jlpmapp:main
        - jupyter-lab = jupyterlab.labapp:main
        - jupyter-labextension = jupyterlab.labextensions:main
        - jupyter-labhub = jupyterlab.labhubapp:main
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/jupyterlab_1586212338938/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install --install-option="--skip-npm" . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py38h32f6830_0
        - icu 64.2 he1b5a44_1
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuv 1.34.0 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - nodejs 13.10.1 hf5d1a2b_0
        - openssl 1.1.1f h516909a_0
        - pip 20.0.2 py_2
        - python 3.8.2 h8356626_5_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.3 py38h32f6830_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zlib 1.2.11 h516909a_1006
    run:
        - jinja2 >=2.10
        - jupyterlab_server >=1.0.0,<2.0.0
        - notebook >=4.3.1
        - python >=3.5
        - tornado !=6.0.0,!=6.0.1,!=6.0.2
test:
    commands:
        - jupyter lab --version
        - jlpm --version
        - jlpm versions
        - jupyter labextension list
        - jupyter lab path
        - jupyter lab build
        - jupyter lab clean
    imports:
        - jupyterlab
    requires:
        - nodejs >=10
about:
    description: 'JupyterLab is the next-generation user interface for Project Jupyter.
        It offers all the familiar building blocks of the classic Jupyter Notebook
        (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible
        and powerful user inteface. Eventually, JupyterLab will replace the classic
        Jupyter Notebook.

        JupyterLab can be extended using extensions that are npm packages and use
        our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension`
        to find extensions. To learn more about extensions, see our user documentation.

        JupyterLab is suitable for general usage. For JupyterLab extension developers,
        the extension APIs will continue to evolve.

        '
    dev_url: https://github.com/jupyterlab/jupyterlab
    doc_url: https://jupyterlab.readthedocs.io
    home: https://github.com/jupyterlab/jupyterlab
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'An extensible environment for interactive and reproducible computing,
        based on the Jupyter Notebook and Architecture.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - afshin
        - blink1073
        - ellisonbg
        - ian-r-rose
        - jasongrout
        - jochym
        - saulshanabrook
