name: data-science 
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - pip
  - mamba
  - jupyterhub
  - jupyterlab
  - dask=2022.4.0
  - distributed=2022.4.0
  - dask-labextension
  - nbgitpuller
  - nodejs
  - s3fs
  - pandas
  - numpy
  - streamlit
  #- pip:
  #  - scikeras
  #  - streamlit-aggrid
