name: Run golint-ci

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v0.2.0
      with:
        version: v1.26
